services:

  rembg:
    restart: unless-stopped
    image: danielgatis/rembg:latest
    command:
      - s
    volumes:
      - ./rembg_data:/root/.u2net
    ports:
      - "127.0.0.1:5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "50k"

  rembg-bot:
    restart: "unless-stopped"
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: xxx
    volumes:
      - .:/app
    depends_on:
      - rembg
      - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "50k"

  mariadb:
    restart: unless-stopped
    image: mariadb:10.5
    cpus: 0.1
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=rembg
      - MYSQL_USER=rembg_user
      - MYSQL_PASSWORD=rembg_pass
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
